# Vertex serves generative models from three shapes of endpoint, and the location
# is what picks between them: a single region (europe-west4), one of the two
# multi-regions (eu, us), or global. Only the regional and multi-region
# endpoints carry a data residency commitment - global explicitly does not, and
# routes requests anywhere in the world. The eu multi-region covers EU member
# states only; the UK and Switzerland are outside it.
# https://docs.cloud.google.com/vertex-ai/generative-ai/docs/learn/data-residency
GOOGLE_VERTEX_DEFAULT_LOCATION = "global"

# Deliberately only the three locations that decide the residency question.
# Individual regions vary in which models they serve and would go stale here, so
# operators who need one type it in rather than picking it from a list that
# claims more than we can keep true.
GOOGLE_VERTEX_LOCATIONS = (GOOGLE_VERTEX_DEFAULT_LOCATION, "eu", "us")

GOOGLE_MODELS = (
    "gemini-3.5-flash",
    "gemini-3.5-flash-lite",
)
# Vertex AI serves three model families through one provider: Gemini (native
# google-genai API), Anthropic Claude (native Anthropic API), and open MaaS
# models (OpenAI-compatible endpoint, ids shaped "{publisher}/{model}-maas").
# The runtime picks the right service per model in service_factory.
GOOGLE_VERTEX_MODELS = (
    # Gemini
    "gemini-3.1-flash-lite",
    "gemini-3.5-flash",
    "gemini-3.5-flash-lite",
    "gemini-3.5-pro",
    # Anthropic Claude
    "claude-haiku-4-5@20251001",
    "claude-sonnet-4-6",
    "claude-sonnet-5",
    # Meta Llama (MaaS)
    "meta/llama-3.3-70b-instruct-maas",
    "meta/llama-4-scout-17b-16e-instruct-maas",
    "meta/llama-4-maverick-17b-128e-instruct-maas",
    # DeepSeek (MaaS)
    "deepseek-ai/deepseek-v3.2-maas",
    "deepseek-ai/deepseek-r1-0528-maas",
    # Qwen (MaaS)
    "qwen/qwen3-next-80b-a3b-instruct-maas",
    "qwen/qwen3-coder-480b-a35b-instruct-maas",
    "qwen/qwen3-235b-a22b-instruct-2507-maas",
    # OpenAI open-weight (MaaS)
    "openai/gpt-oss-120b-maas",
    "openai/gpt-oss-20b-maas",
    # Moonshot / MiniMax (MaaS)
    "moonshotai/kimi-k2-thinking-maas",
    "minimax/minimax-m2-maas",
)

GOOGLE_REALTIME_MODELS = (
    "gemini-3.8-live",
    "gemini-3.1-flash-live-preview",
)
GOOGLE_REALTIME_VOICES = ("Puck", "Charon", "Kore", "Fenrir", "Aoede")
GOOGLE_REALTIME_LANGUAGES = (
    "ar",
    "bn",
    "de",
    "en",
    "es",
    "fr",
    "gu",
    "hi",
    "id",
    "it",
    "ja",
    "kn",
    "ko",
    "ml",
    "mr",
    "nl",
    "pl",
    "pt",
    "ru",
    "ta",
    "te",
    "th",
    "tr",
    "vi",
    "zh",
)

GOOGLE_VERTEX_REALTIME_MODELS = ("google/gemini-live-2.5-flash-native-audio",)
GOOGLE_VERTEX_REALTIME_VOICES = GOOGLE_REALTIME_VOICES
GOOGLE_VERTEX_REALTIME_LANGUAGES = GOOGLE_REALTIME_LANGUAGES

GOOGLE_STT_MODELS = ("latest_long", "latest_short", "chirp_3")
# Docs-derived from Google Cloud Speech-to-Text V2 supported languages.
GOOGLE_STT_LANGUAGES = (
    "af-ZA",
    "am-ET",
    "ar-AE",
    "ar-BH",
    "ar-DZ",
    "ar-EG",
    "ar-IL",
    "ar-IQ",
    "ar-JO",
    "ar-KW",
    "ar-LB",
    "ar-MA",
    "ar-MR",
    "ar-OM",
    "ar-PS",
    "ar-QA",
    "ar-SA",
    "ar-SY",
    "ar-TN",
    "ar-XA",
    "ar-YE",
    "as-IN",
    "ast-ES",
    "az-AZ",
    "be-BY",
    "bg-BG",
    "bn-BD",
    "bn-IN",
    "bs-BA",
    "ca-ES",
    "ceb-PH",
    "ckb-IQ",
    "cmn-Hans-CN",
    "cmn-Hant-TW",
    "cs-CZ",
    "cy-GB",
    "da-DK",
    "de-AT",
    "de-CH",
    "de-DE",
    "el-GR",
    "en-AU",
    "en-GB",
    "en-HK",
    "en-IE",
    "en-IN",
    "en-NZ",
    "en-PH",
    "en-PK",
    "en-SG",
    "en-US",
    "es-419",
    "es-AR",
    "es-BO",
    "es-CL",
    "es-CO",
    "es-CR",
    "es-DO",
    "es-EC",
    "es-ES",
    "es-GT",
    "es-HN",
    "es-MX",
    "es-NI",
    "es-PA",
    "es-PE",
    "es-PR",
    "es-SV",
    "es-US",
    "es-UY",
    "es-VE",
    "et-EE",
    "eu-ES",
    "fa-IR",
    "ff-SN",
    "fi-FI",
    "fil-PH",
    "fr-BE",
    "fr-CA",
    "fr-CH",
    "fr-FR",
    "ga-IE",
    "gl-ES",
    "gu-IN",
    "ha-NG",
    "hi-IN",
    "hr-HR",
    "hu-HU",
    "hy-AM",
    "id-ID",
    "ig-NG",
    "is-IS",
    "it-CH",
    "it-IT",
    "iw-IL",
    "ja-JP",
    "jv-ID",
    "ka-GE",
    "kam-KE",
    "kea-CV",
    "kk-KZ",
    "km-KH",
    "kn-IN",
    "ko-KR",
    "ky-KG",
    "lb-LU",
    "lg-UG",
    "ln-CD",
    "lo-LA",
    "lt-LT",
    "luo-KE",
    "lv-LV",
    "mi-NZ",
    "mk-MK",
    "ml-IN",
    "mn-MN",
    "mr-IN",
    "ms-MY",
    "mt-MT",
    "my-MM",
    "ne-NP",
    "nl-BE",
    "nl-NL",
    "no-NO",
    "nso-ZA",
    "ny-MW",
    "oc-FR",
    "om-ET",
    "or-IN",
    "pa-Guru-IN",
    "pl-PL",
    "ps-AF",
    "pt-BR",
    "pt-PT",
    "ro-RO",
    "ru-RU",
    "rup-BG",
    "rw-RW",
    "sd-IN",
    "si-LK",
    "sk-SK",
    "sl-SI",
    "sn-ZW",
    "so-SO",
    "sq-AL",
    "sr-RS",
    "ss-Latn-ZA",
    "st-ZA",
    "su-ID",
    "sv-SE",
    "sw",
    "sw-KE",
    "ta-IN",
    "te-IN",
    "tg-TJ",
    "th-TH",
    "tn-Latn-ZA",
    "tr-TR",
    "ts-ZA",
    "uk-UA",
    "umb-AO",
    "ur-PK",
    "uz-UZ",
    "ve-ZA",
    "vi-VN",
    "wo-SN",
    "xh-ZA",
    "yo-NG",
    "yue-Hant-HK",
    "zu-ZA",
)

GOOGLE_TTS_MODELS = ("chirp_3_hd",)
GOOGLE_TTS_VOICES = ("en-US-Chirp3-HD-Charon",)
GOOGLE_TTS_LANGUAGES = (
    "ar-XA",
    "bn-IN",
    "bg-BG",
    "yue-HK",
    "hr-HR",
    "cs-CZ",
    "da-DK",
    "nl-BE",
    "nl-NL",
    "en-AU",
    "en-IN",
    "en-GB",
    "en-US",
    "et-EE",
    "fi-FI",
    "fr-CA",
    "fr-FR",
    "de-DE",
    "el-GR",
    "gu-IN",
    "he-IL",
    "hi-IN",
    "hu-HU",
    "id-ID",
    "it-IT",
    "ja-JP",
    "kn-IN",
    "ko-KR",
    "lv-LV",
    "lt-LT",
    "ml-IN",
    "cmn-CN",
    "mr-IN",
    "nb-NO",
    "pl-PL",
    "pt-BR",
    "pa-IN",
    "ro-RO",
    "ru-RU",
    "sr-RS",
    "sk-SK",
    "sl-SI",
    "es-ES",
    "es-US",
    "sw-KE",
    "sv-SE",
    "ta-IN",
    "te-IN",
    "th-TH",
    "tr-TR",
    "uk-UA",
    "ur-IN",
    "vi-VN",
)
